authority: "https://login.microsoftonline.com"
graphurl: "https://graph.microsoft.com/.default"
DB_HOST: "localhost"
DB_NAME: "yourdbname"
DB_USER: "someuser"
DB_PASS: "password"
SECRET_KEY: "your_random_secret_key"
tenant_id: "u2zb9z7i-9pf4-4doo-2k2k-dabolvm8080q"
client_id: "s0meran4-0m70-j007-mi60-jamesvm7070q"
client_secret: "xUjzs~2ZLH1597MQ65C31S9YQMU577EAO2-OjGrC"
mail_username: "mailusername"
mail_password: "mailpassword"
logfile_savelocation: "/path/to/save/azurelogs/"
interval_minutes: 60
mail_server: "smtp.somemailserver.com"
mail_port: 2525
mail_use_tls: True
mail_use_ssl: False
mail_default_sender: ""
mail_max_emails: None
mail_ascii_attachments: False
mail_sender: "AzuregroupmonitorApp@somecompanyname.com"
mail_recipient: "azureadmins@somecompanyname.com"
